import type { CnaeInfo } from '@/types/tributario'

export const CURATED_CNAES: CnaeInfo[] = [
  { cnae: '6201-5/01', descricao: 'Desenvolvimento de programas de computador sob encomenda', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6201-5/02', descricao: 'Web design', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6202-3/00', descricao: 'Desenvolvimento e licenciamento de programas de computador customizáveis', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6203-1/00', descricao: 'Desenvolvimento e licenciamento de programas de computador não customizáveis', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6204-0/00', descricao: 'Consultoria em tecnologia da informação', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6209-1/00', descricao: 'Suporte técnico, manutenção e outros serviços em TI', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6311-9/00', descricao: 'Tratamento de dados, provedores de serviços de aplicação e hospedagem', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6319-4/00', descricao: 'Portais, provedores de conteúdo e outros serviços de informação na internet', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7020-4/00', descricao: 'Atividades de consultoria em gestão empresarial', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7112-0/00', descricao: 'Atividades de engenharia e afins', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7111-1/00', descricao: 'Atividades de arquitetura', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7311-4/00', descricao: 'Agências de publicidade', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7319-0/02', descricao: 'Promoção de vendas', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7410-2/02', descricao: 'Design gráfico', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7410-2/03', descricao: 'Design de produto', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6920-6/01', descricao: 'Atividades de contabilidade', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '6920-6/02', descricao: 'Atividades de consultoria e auditoria contábil e tributária', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '7490-1/04', descricao: 'Atividades de intermediação e agenciamento de serviços', anexoPadrao: 'V', elegivelFatorR: true, categoria: 'ti_consultoria' },
  { cnae: '8599-6/04', descricao: 'Treinamento em desenvolvimento profissional e gerencial', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '8599-6/99', descricao: 'Outras atividades de ensino não especificadas', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '8630-5/04', descricao: 'Atividades de fisioterapia', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '9602-5/01', descricao: 'Cabeleireiros', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '9602-5/02', descricao: 'Manicure e pedicure', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '7500-1/00', descricao: 'Atividades veterinárias', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '8011-1/01', descricao: 'Atividades de vigilância e segurança privada', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '5611-2/01', descricao: 'Restaurantes e similares', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '4712-1/00', descricao: 'Comércio varejista de mercadorias em geral', anexoPadrao: 'I', elegivelFatorR: false, categoria: 'comercio' },
  { cnae: '4751-2/01', descricao: 'Comércio varejista especializado de equipamentos e suprimentos de informática', anexoPadrao: 'I', elegivelFatorR: false, categoria: 'comercio' },
  { cnae: '4771-7/01', descricao: 'Comércio varejista de produtos farmacêuticos', anexoPadrao: 'I', elegivelFatorR: false, categoria: 'comercio' },
  { cnae: '4930-2/02', descricao: 'Transporte rodoviário de carga, exceto produtos perigosos e mudanças, intermunicipal, interestadual e internacional', anexoPadrao: 'III', elegivelFatorR: false, categoria: 'servicos' },
  { cnae: '4120-4/00', descricao: 'Construção de edifícios', anexoPadrao: 'IV', elegivelFatorR: false, categoria: 'construcao' },
  { cnae: '6911-7/01', descricao: 'Serviços advocatícios', anexoPadrao: 'IV', elegivelFatorR: false, categoria: 'construcao' },
  { cnae: '8121-4/00', descricao: 'Limpeza em prédios e em domicílios', anexoPadrao: 'IV', elegivelFatorR: false, categoria: 'construcao' },
]

export const CURATED_CNAE_INDEX: Map<string, CnaeInfo> = new Map(
  CURATED_CNAES.map(item => [item.cnae, item]),
)
